# Setup
title:               'Jam's Blog'
tagline:             'All my knownledge'
description:         'Solutions of problems I met'
url:                 http://wodadehencou.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jam Adams
  url:               ''
  email:             wodadehencou@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
